name: chai
description: Reward based application

publish_to: 'none' 

version: 0.0.7

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.3.2
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  google_fonts: ^4.0.3
  google_sign_in: ^5.4.4
  introduction_screen: ^3.1.4
  swipeable_page_route: ^0.3.0
  url_launcher: ^6.1.9
  flutter_secure_storage: ^8.0.0
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/src/assets/

flutter_icons:
  android: "launcher_icon"
  image_path: "lib/src/assets/chai_final.jpg"